### ISSUE TITLE
Cannot import ffn for matplotlib.use removed warn

### ISSUE THREAD

**Issue by Poeticphysicist** [pmorissette/ffn#101]
From ffn core scripts, we should import matplotlib first as :
"""
if 'DISPLAY' not in os.environ:
    matplotlib.use('agg', warn=False)
"""
But "warn=False" has been removed... So error occurred.

**Comment by r0f1** [comment]
Workaround:
```
os.environ["DISPLAY"] = ""
import ffn
```

**Comment by eervin123** [comment]
Thank you this is helpful, @r0f1

**Comment by timkpaine** [comment]
closing as there is a workaround. the justification for this is provided `# avoid pyplot import failure in headless environment`, PRs welcome for a better/more permanent workaround.
