### ISSUE TITLE
FFN import - "cannot import name 'urlencode'".

### ISSUE THREAD

**Issue by EdoardoFF** [pmorissette/ffn#103]
Hi,

I have the 3.4.2 and, once I try to import FFN, I get: 
"cannot import name 'urlencode'".

I also import

import numpy as np
import pandas as pd
import os
import glob
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

import cufflinks as cf

Where am I wrong?

**Comment by timkpaine** [comment]
can you provide a stack trace

**Comment by EdoardoFF** [comment]
Hi Tim,

It was just an update..

I have another issue

After having imported ffn, I retrieve data, using the required instructions:

data = ffn.get('spy', start='2000-08-30', end='2020-08-30')
data.head(10)

perf = data.calc_stats()

*and no problem so far, but when I try to display monthly return, I get
this message:*

perf['spy'].display_monthly_returns() . I also have attached an image of
the jupiter screen. I had no problems with other functions, only for this
one.

Thanks for your help!


AttributeError                            Traceback (most recent call
last)<ipython-input-7-051d4b3befc7> in <module>()----> 1
perf['spy'].display_monthly_returns()
~\Anaconda3\lib\site-packages\ffn\core.py in
display_monthly_returns(self)    499                  'Jun', 'Jul',
'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'YTD']]    500         for k in
self.return_table.index:--> 501             r =
self.return_table.ix[k].values    502             data.append([k] +
[fmtpn(x) for x in r])    503         print(tabulate(data,
headers='firstrow'))
~\Anaconda3\lib\site-packages\pandas\core\generic.py in
__getattr__(self, name)   5137             if
self._info_axis._can_hold_identifiers_and_holds_name(name):   5138
            return self[name]-> 5139             return
object.__getattribute__(self, name)   5140    5141     def
__setattr__(self, name: str, value) -> None:
AttributeError: 'DataFrame' object has no attribute 'ix'


Il giorno sab 21 nov 2020 alle ore 23:14 Tim Paine <notifications@github.com>
ha scritto:

**Comment by timkpaine** [comment]
https://github.com/pmorissette/ffn/pull/61
