### ISSUE TITLE
'DataFrame' object has no attribute 'ix'

### ISSUE THREAD

**Issue by pacov** [pmorissette/ffn#107]
perf[2].display_monthly_returns() 
is not running

**Comment by eervin123** [comment]
.ix is deprecated in the new pandas release.  Change .ix to .iloc and everything should work correctly.

**Comment by eervin123** [comment]
@timkpaine  I just updated my response, It appears this is a PyPI issue, not a code bug.  I think the newer release just needs to be pushed.

**Comment by eervin123** [comment]
It appears this was fixed in 2018

**Comment by pacov** [comment]
Thank you very much. I’ll update PyPI.

**Comment by timkpaine** [comment]
closing, will do a release in the nearish future. Feel free to use an older version of pandas in the mean time.
