### ISSUE TITLE
The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.

### ISSUE THREAD

**Issue by MatteoSid** [pmorissette/ffn#110]
When I import fan I have this error. I've tried to update fun.

`/opt/anaconda3/lib/python3.8/site-packages/ffn/core.py:27: MatplotlibDeprecationWarning:

The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.`

**Comment by timkpaine** [comment]
Is this fixed by https://github.com/pmorissette/ffn/pull/104/files

**Comment by MatteoSid** [comment]
> Is this fixed by https://github.com/pmorissette/ffn/pull/104/files

I don't know how to fix, if I update MatPlotLib to the v3.3.3 I can't use ffn

**Comment by timkpaine** [comment]
try ffn off master

**Comment by MatteoSid** [comment]
@timkpaine Thank you but I don't know what 'fun off master' is and how to use it. 🤔

**Comment by timkpaine** [comment]
build and install ffn using this repo. 

This is fixed in #104

**Comment by MatteoSid** [comment]
I'm really sorry but I don't know what "build and install ffn using this repo" means. I installed fan with pip install ffn but I can't use it with mpl 3.3.3 so I need to downgrade it to 3.2.0 but I have errors or warnings. :/

**Comment by timkpaine** [comment]
Google how to install a project from GitHub.
