### ISSUE TITLE
importing ffn failed

### ISSUE THREAD

**Issue by Kerberos007** [pmorissette/ffn#126]
I am getting below error when doing "import ffn" -- NameError: name 'utils' is not defined
thanks in advance.

_init__.py in <module>
      1 from . import core
----> 2 from . import data
      3 
      4 from .data import get
      5 #from .core import year_frac, PerformanceStats, GroupStats, merge

..\ffn\data.py in <module>
    199 
    200 
--> 201 @utils.memoize
    202 def get(tickers, provider=None, common_dates=True, forward_fill=False,
    203         clean_tickers=True, column_names=None, ticker_field_sep=':',

NameError: name 'utils' is not defined

**Comment by timkpaine** [comment]
I cannot reproduce. please provide some more info and ideally a mechanism to reproduce in a clean virtualenv.
