### ISSUE TITLE
resample() error

### ISSUE THREAD

**Issue by denbjornen** [pmorissette/ffn#13]
I'm running python 2.7 and I'm not sure if this has something to do with it.. But I'm having an issue with the "core.py" file. Not sure what part of ffn is calling "core.py" but its having a problem with the resample() function. Apparently the "how" part of the function has been replaced with a new syntax. After looking at the documentation, I was able to fix this problem by navigating to the "core.py" file in ffn of the python folder and change lines 189 & 191 to: (respectively)

self.monthly_prices = obj.resample('M').last()

self.monthly_prices = obj.resample('A').last()

**Comment by JordanPlatts** [comment]
I think this may be handled now.
