### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by masmox** [pmorissette/ffn#146]
Hello,

I'm using Python 3.8 and PyCharm 2021.1.1.
When I use ffn (0.3.6) to get aapl ticker using the following code:

import ffn

dataset_ffn = ffn.get('aapl', start='2018-01-01')
dataset_ffn.columns = ["open", "high", "low", "close"]
print(dataset_ffn.tail(10))

the following messages I catch

Traceback (most recent call last):
  File "C:/Users/username/PycharmProjects/Examples/ffn_example.py", line 5, in <module>
    dataset_ffn = ffn.get('aapl', start='2018-01-01')
  File "C:\Users\username\Anaconda3\lib\site-packages\decorator.py", line 231, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\username\Anaconda3\lib\site-packages\ffn\utils.py", line 20, in _memoize
    if args[func.__code__.co_varnames.index(refresh_kw)]:
IndexError: tuple index out of range

Process finished with exit code 1

Also, if I use Jupyter Notebook I catch the same error.

Please can you give me a support?

Thanks.

**Comment by kiesoman** [comment]
I hope to know the solution, too.
I think this problem is from yahoo change.
could anyone has idea?
thanks  first.

**Comment by roywwei** [comment]
ffn should be compatible with Python 2.7.

**Comment by applebg** [comment]
I also ran into problem. I use Jupyter notebook. Here is my code:
`import ffn
prices = ffn.get('aapl', start='2010-01-01')`

I got "IndexError: tuple index out of range". Does it mean the code could actually acquire data, but somehow the format of data is not what the code had expected?

**Comment by marcusfin** [comment]
Ciao,
same error here with the code "pasted" exactly as in the example : import ffn
returns = ffn.get('aapl,msft,c,gs,ge', start='2010-01-01').to_returns().dropna()
returns.calc_mean_var_weights().as_format('.2%') 
IndexError: tuple index out of range
Thanks in advance for support
Ciao

![Capture](https://user-images.githubusercontent.com/28948176/134687166-e0cb4741-83c5-4120-b534-9f8bb1fc1c2b.PNG)

**Comment by cbozzetto** [comment]
Had the same issue today. 
I use JupyterNotebook as part of an anaconda environment. Running `conda update --all` on terminal solved it.

**Comment by timkpaine** [comment]
https://github.com/pmorissette/ffn/pull/216
