### ISSUE TITLE
pandas_datareader._utils.RemoteDataError

### ISSUE THREAD

**Issue by terrysclaw** [pmorissette/ffn#149]
prices = ffn.get('aapl,msft', start='2010-01-01')

pandas_datareader._utils.RemoteDataError: Unable to read URL: https://finance.yahoo.com/quote/aapl/history?period1=1262289600&period2=1625342399&interval=1d&frequency=1d&filter=history

Is yahoo off?

**Comment by timkpaine** [comment]
Duplicate
