### ISSUE TITLE
 Unable to read URL: https://finance.yahoo.com/quote/alf/history?period1=1623988800&period2=1641009599&interval=1d&frequency=1d&filter=history

### ISSUE THREAD

**Issue by kramerdanny** [pmorissette/ffn#151]
The module FFN retrieved stock data from YAHOO but YAHOO stopped providing this service.
Is there a way to retrieve stock data from another provider like ALPHA VANTAGE or Twelve Data (as an example only).

Thank you in advance,

Daniel K

**Comment by HubertTW** [comment]
you have to upgrade your pandas_datareader package by pip
and then you can get the yahoo data as usual ~

`pip install --upgrade pandas_datareader`
