### ISSUE TITLE
NameError: name 'stats' is not defined

### ISSUE THREAD

**Issue by akitxu** [pmorissette/ffn#159]
Dear All

When I executing the sentence       `ax = stats.df_valor.to_drawdown_series().plot()`

it returns the error
`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-77-70be1a37e828> in <module>
      1 # what about the drawdowns?
----> 2 ax = stats.df_valor.to_drawdown_series().plot()

NameError: name 'stats' is not defined

1

 `
Imported módules: 

`....
from scipy.stats import skew,kurtosis,norm,skewtest,kurtosistest
....`

What can be the cause?. I will appreciate help.

**Comment by mdengler** [comment]
What `stats` are you working with?  Perhaps you meant `ffn.core.to_drawdown_series(df_valor)`?
