### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Allensususu** [pmorissette/ffn#185]
Hi 

Today, when I was using ffn, I found that an error would be reported. After checking, it should be that the information obtained by yahoo finance has been revised. Could you please check it?

Here is the discussion I found
https://stackoverflow.com/questions/74832296/typeerror-string-indices-must-be-integers-when-getting-data-of-a-stock-from-y

thank you very much

**Comment by GiovaMille** [comment]
Just to provide more details, I run the example that pmorisette suggest in the FFN overview. In the attached file you can fine the complete error output.


[FFN-outcome.pdf](https://github.com/pmorissette/ffn/files/10267331/FFN-outcome.pdf)

**Comment by Allensususu** [comment]
I fix it with "yfinance.pdr_override()" .

you can add 
`    #import yfinance 
    #yfinance.pdr_override()`
in data.py 142 lines.

like this :
![image](https://user-images.githubusercontent.com/46346226/208663056-d5d06f55-806b-4758-be8b-d6c9d73c95ab.png)

**Comment by GiovaMille** [comment]
> `import yfinance`
> ` yfinance.pdr_override()`

It worked! Thank you!

**Comment by gerrymarrk** [comment]
import yfinance
   yfinance.pdr_override()
It works for me as well, really appreciated!!
