### ISSUE TITLE
Is it possible in FFN to load Bloomberg stock data?

### ISSUE THREAD

**Issue by tianqig** [pmorissette/ffn#20]
Wonder if it is possible to use FFN to load stock data from Bloomberg source? or how to setup the data source from Yahoo to Bloomberg?

Thanks

**Comment by pmorissette** [comment]
Currently, `ffn` uses `pandas_datareader` to load external data. Please refer to that project's documentation for support on different data sources. Alternatively, you might be able to find another library that can do this (not sure if you are referring to the Bloomberg website or Bloomberg Terminal). 

Anyways, at the end of the day, you just need to get your data in a `pandas` object (`Series`, `DataFrame`) and the rest of the functions in the library will still work as expected.

Cheers,
Phil
