### ISSUE TITLE
in python 11,there are some warnings about ffn

### ISSUE THREAD

**Issue by vagrant-psyche** [pmorissette/ffn#217]
**Describe the bug**
in python 11,there are some warnings about ffn

/root/miniconda3/envs/general/lib/python3.11/site-packages/ffn/core.py:1258: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return daily_prices[-1] / monthly_prices[-2] - 1

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/pmorissette/ffn/assets/37809377/fa82a6c7-fb25-4bf2-bcaf-86b8392a7832)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Version:python 11

**Additional context**

**Comment by timkpaine** [comment]
https://github.com/pmorissette/ffn/pull/202
