### ISSUE TITLE
RemoteDataError: Unable to read URL

### ISSUE THREAD

**Issue by tsando** [pmorissette/ffn#22]
Hi,

I am running this on Python 3.5:
`
ffn.get('aapl,msft,c,gs,ge', start='2010-01-01').to_returns().dropna()`

But I get the folllowing error:
`
RemoteDataError: Unable to read URL: http://ichart.finance.yahoo.com/table.csv?f=2017&g=d&e=20&c=2010&d=2&s=aapl&a=0&b=1&ignore=.csv
`

Any ideas of how to solve this? Thanks.

**Comment by ManuelLevi** [comment]
I think this is a problem with Yahoo API.

Both yahoo_finance and pandas_datareader (which is used in this project) seem to be broken because of it.

**Comment by pmorissette** [comment]
Yes this problem is external to `ffn`. I believe the YahooFinance API has been discontinued. I will switch over to a different default provider if this is indeed the case.

**Comment by ManuelLevi** [comment]
If you change the default from yahoo to google it should work.

**Comment by pmorissette** [comment]
fixed by 07e6df0e8084c5f6c08c8a4430fa956af41d7656
