### ISSUE TITLE
A ffn.get() issue in Python 3.12.2 with ffn 1.1.0

### ISSUE THREAD

**Issue by JeffreyChang168** [pmorissette/ffn#250]
**Describe the bug**
In VS Code, we tried to use Python 3.12.2 with ffn 1.1.0 and encountered the following
error "ValueError: If using all scalar values, you must pass an index"..

**To Reproduce**

1. import ffn  # ffn 1.1.0
2. returns = ffn.get('aapl,msft,c,gs,ge', start='2010-01-01').to_returns().dropna()

**Expected behavior**

**Screenshots**
![Error_01-vert](https://github.com/user-attachments/assets/30b3a272-89f1-4edd-88bb-6141a874e9d9)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code 1.95.0
 - Python 3.12.2
 - ffn 1.1.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by simoneb** [comment]
Same here

**Comment by quant12345** [comment]
Python 3.12, Pandas 2.2.3, ffn 1.1.0, PyCharm. I can't reproduce the error. But I can say it's most likely Pandas, where a dataframe with one row is created based on scalars. Something like that.

**Comment by Luavis** [comment]
I didn't test all of the versions. but the problem of this issues come from yfinance module. ffn.get call yfinance.
I think there are some changes of dataframe shape after it upgraded.

If you fix the yfinance module version to 0.2.44. In my case it was fixed.
