### ISSUE TITLE
Arguments for performance function

### ISSUE THREAD

**Issue by SteffenNa** [pmorissette/ffn#27]
Hi. I am looking to the get performance stats for a Pandas DF of monthly returns. Seems this is not possible -correct? Do you have any plans to add this? (Novice programmer -so please forgive me for the stupid question)

**Comment by JordanPlatts** [comment]
Convert your return dataframe into an index dataframe

     pdf = np.cumprod(1+df)
     pdf.iloc[0,:] = 1.
