### ISSUE TITLE
Documentation: Links to term explainers?

### ISSUE THREAD

**Issue by noodlefrenzy** [pmorissette/ffn#48]
Hey, I'm using your library as a method to learn various fintech methods and experiment, and have been reading your documentation and spending time looking up various terms in Investopedia. I think it'd be useful to have links from your documentation directly to explanations of the various terms (e.g. Calman Ratio).

I'm willing to do the work and submit the PR, but wanted to check with you first whether that's something you would appreciate/find useful.

**Comment by noodlefrenzy** [comment]
P.S. I would also be willing to do the same for `bt`. Thanks for authoring! These libraries have been incredibly helpful.

**Comment by JordanPlatts** [comment]
I think that would be a great idea! I am sure a lot of people would find it useful and it will make the library more user friendly. Thanks for helping out.

**Comment by noodlefrenzy** [comment]
😺 excellent, I'll get right on it... tomorrow. Hopefully you'll see a PR soon. :shipit:

**Comment by noodlefrenzy** [comment]
Closed with #49
