### ISSUE TITLE
ImportError: cannot import name core

### ISSUE THREAD

**Issue by ymkarthi** [pmorissette/ffn#58]
Hi,
I am new to Python and when i am trying to set up ffn, i get the above error. Can you please help?

**Comment by stephanepiriou** [comment]
I have the same kind of issue related to import of core. 

I tried the first example on the README.

According to a thread on stackoverflow, it''s related to the version of Pandas or DataReader and could be solved by downgrading one of the 2 packages or changing the import in the library.

**Comment by JordanPlatts** [comment]
Check out issue #55 and let me know if that solves the problem.

**Comment by timkpaine** [comment]
closing, stale.
