### ISSUE TITLE
Starting with returns. 

### ISSUE THREAD

**Issue by csc5a2g** [pmorissette/ffn#68]
Hi All,

Having looked at FFN I'm keen to try it out to see the performance statistics of my trading strategy, however it looks like the I can only start with prices rather than returns. 

How can I use FFN with the returns from my trading strategy (a basic example would be amazing) ?

D

**Comment by svenissimo** [comment]
I'm just a lurker here but if you have Arithmetic Returns you can just use the following and supply a starting price(although that won't really matter)
http://pmorissette.github.io/ffn/ffn.html#ffn.core.to_price_index  

if you are supplying log returns then I can't really help but imagine it involves the inverse of 'log'

**Comment by csc5a2g** [comment]
Thank svenissimo. Sorted.
