### ISSUE TITLE
Import Error cannot import name 'core' from 'numpy' on Jupyter Notebook

### ISSUE THREAD

**Issue by anhquanhua189** [pmorissette/ffn#72]
Hi guys, i'm a student who is totally new to Python3 and have no previous experience in coding. I installed Anaconda 3.7 Python and opened Jupyter Notebook to do some of my work. While i was trying to import Numpy, this error popped up at the bottom. 

ImportError: cannot import name 'core' from 'numpy'

I've tried to look everywhere but it hasn't got any luck.

**Comment by mmmeeeker** [comment]
It seems as though this is an issue with numpy, rather than with ffn.

Seeing as this is an Import Error, and you've stated that you're new to Python, did you ensure that you have NumPy imported as well? There are several dependencies (NumPy being one of them) for this library.

**Comment by timkpaine** [comment]
not related to this library
