### ISSUE TITLE
how to write the output of df_prices.calc_stats() to pdf or doc?

### ISSUE THREAD

**Issue by summorwenluo** [pmorissette/ffn#77]
I'd like to write the output of df_prices.calc_stats() to pdf or doc. But I cannot find a way to achieve it.

**Comment by leogregianin** [comment]
@summorwenluo, if you use Jupyter Notebook, you can save your results in several file format including HTML, PDF, Markdown, and others.

**Comment by timkpaine** [comment]
this isn't relevant for this project.
