### ISSUE TITLE
bug: plot_scatter_matrix

### ISSUE THREAD

**Issue by simjason** [pmorissette/ffn#82]
In plot scatter matrix:

  pd.scatter_matrix(ser, figsize=figsize, **kwargs)

needs to be:

  pd.plotting.scatter_matrix(ser, figsize=figsize, **kwargs)

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.plotting.scatter_matrix.html

**Comment by y26805** [comment]
duplicate of https://github.com/pmorissette/ffn/issues/76

**Comment by y26805** [comment]
technically not a bug but a feature, since `requirements.txt` rightly specified 0.22.0
https://github.com/pmorissette/ffn/blob/ef86a714afbb6dab8fcbb897de4a4553f76e8073/requirements.txt#L4
