### ISSUE TITLE
display_monthly_returns incorrect ?

### ISSUE THREAD

**Issue by csc5a2g** [pmorissette/ffn#86]
Hi,

I'm using to FFN to get an idea of my strategies monthly performance and I think generating the wrong date when I call "display_monthly_returns":

  Year    Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct    Nov    Dec    YTD
------  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----  -----
  2000   3.45  10.34   5.51  -0.08   1.59   2.55   0.84   1.55   4.79   1.16   1.19   5.03  44.63

The above is the first year of my strategy and the YTD is not the sum of all the individual months as reported above. It's 37.92.

What am I missing ?

Thanks
A

**Comment by zenzeizen** [comment]
You are correct that the sum of the numbers provided is 37.92. That is the arithmetic mean of the numbers. The geometric mean of that time series is in fact 44.6%.

In finance, the more interesting number is the geometric mean. The geometric mean takes into account the compounding of money.

[Investopedia Article on Arithmetic vs Geometric Mean](https://www.investopedia.com/ask/answers/06/geometricmean.asp)

**Comment by csc5a2g** [comment]
Thanks.
